name: efood_multivendor_restaurant
description: An application for multivendor ecommerce restaurant.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  shared_preferences: ^2.0.6
  connectivity: ^3.0.6
  firebase_core: any
  firebase_messaging: any
  flutter_local_notifications: ^9.5.3+1
  path_provider: ^2.0.2
  url_strategy: ^0.2.0
  shimmer_animation: ^2.0.0
  image_picker: ^0.8.0+4
  http: ^0.13.3
  pin_code_fields: ^7.2.0
  url_launcher: ^6.1.2
  vibration: ^1.7.6
  audioplayers: ^1.1.1
  flutter_switch: ^0.3.2
  flutter_typeahead: ^4.3.1
  phone_number: ^1.0.0
  country_code_picker: ^2.0.2
  flutter_widget_from_html_core: ^0.8.4
  bluetooth_thermal_printer: ^0.0.6
  esc_pos_utils: ^1.0.0
  fwfh_text_style: ^2.7.2
  image_compression_flutter: ^1.0.2
#  audio_service: ^0.18.9
#  just_audio: ^0.9.31
#  flutter_ringtone_player: ^3.2.0
#  flutter_alarm_background_trigger: ^1.0.0
#  android_alarm_manager_plus: ^2.1.0
#  audio_manager: ^0.8.2

#  blue_thermal_printer: ^1.1.8
#  bluetooth_print: ^3.0.1

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900